### ISSUE TITLE
enhance delivery pipeline

### ISSUE THREAD

**Issue by sebhoss** [metio/ilo#18]
- [x] push releases to bintray (#19)
- [x] sign build artifacts (#20)
- [x] deliver man page (#21)
- [x] integrate 'fuzzit' (#22)
- [x] integrate 'resuse' (#23)
