### ISSUE TITLE
Support LXC/LXD

### ISSUE THREAD

**Issue by sebhoss** [metio/ilo#41]
Umbrella ticket for LXC/LXD support:

- [ ] Allow to remove image (#39)
- [ ] Allow to mount to project directory (#38)
- [ ] Allow to build image locally (#37)
- [ ] Allow to pull image before opening shell (#36)
- [ ] Allow to specify custom commands (#35)
- [ ] Support non-interactive build (#34)
- [ ] Support interactive shell (#33)
